www/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.todolist_overview, name="overview"),
    url(r'^overview/$', views.todolist_overview, name="todolist_overview"),
    url(r'^add/$', views.todolist_add, name="todolist_add"),
    url(r'^delete/(?P<object_id>\d+)/$', views.todolist_delete, name="todolist_delete"),
    url(r'^edit/(?P<object_id>\d+)/$', views.todolist_edit, name="todolist_edit"),
    url(r'^done/(?P<object_id>\d+)/$', views.todolist_done, name="todolist_done"),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
]

www/models.py
from django.db import models

# Create your models here.

www/todolist/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class TodoEntry(models.Model):
	User = models.ForeignKey(User)
	Title = models.CharField(max_length=250, null=False)
	Description = models.CharField(max_length=250, null=True)
	Duedate = models.DateField(blank=True, null=True)
	Duetime = models.TimeField(blank=True, null=True)
	OPEN = 'OPEN'
	DONE = 'DONE'
	Status_Choices = (
		(OPEN, 'OPEN'),
		(DONE, 'DONE'),
	)
	Status = models.CharField(max_length=4, choices=Status_Choices, default=OPEN)

www/todolist/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from www.todolist.models import TodoEntry


class EntryForm(forms.ModelForm):
    Description = forms.CharField(widget=forms.Textarea(attrs={'cols': 40, 'rows': 3}))
    class Meta:
        model = TodoEntry
        fields = ["Title", "Description", "Duedate", "Duetime"]
       # widgets = {
       #    'Description': Textarea(attrs={'cols': 40, 'rows': 3}),
       # }

www/todolist/views.py
from django.shortcuts import render

# Create your views here.

www/views.py
from django.shortcuts import render,HttpResponse, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from www.todolist.models import TodoEntry
from www.todolist.forms import EntryForm
from django.template.context_processors import csrf

# index view (just redirect to login page)
def index(request):
  return HttpResponseRedirect('/login/')

########################################################################################
def todolist_overview(request):
	
	if request.user.id is None:
		return HttpResponseRedirect('/login/')
	open_list = TodoEntry.objects.filter(User = request.user.id, Status='OPEN')
	done_list = TodoEntry.objects.filter(User = request.user.id, Status='DONE')
	if (len(open_list) + len(done_list) > 0):
		percentage = int(100*len(open_list)/(len(open_list)+len(done_list)))
	else:
		percentage = 0
	percentage2= 100-percentage

	return render_to_response("todolist_overview", {"open_list": open_list, "done_list": done_list, "username":request.user.username, "percentage":percentage, "percentage2":percentage2, "opencount": len(open_list), "donecount": len(done_list)})
########################################################################################
def todolist_add(request):
	if request.user.id is  None:
		return HttpResponseRedirect('/login/')
	form = EntryForm(request.POST or None)

	if form.is_valid():
		add_object = TodoEntry()
		add_object.User = request.user
		add_object.Title = form.cleaned_data['Title']
		add_object.Description = form.cleaned_data['Description']
		add_object.Duedate = form.cleaned_data['Duedate']
		add_object.Duetime = form.cleaned_data['Duetime']
		add_object.save()
		return HttpResponseRedirect('/')
	
	return render_to_response("form.html",{"form": form}, context_instance=RequestContext(request))

########################################################################################
def todolist_edit(request, object_id):
	if request.user.id is  None:
		return HttpResponseRedirect('/login/')
	username = request.user
	form = EntryForm(request.POST or None)

	try:
		edit_object = TodoEntry.objects.get(id=object_id)
	except ObjectDoesNotExist, e:
		raise Http404
	print object_id

	if edit_object.User.id == request.user.id:
		if form.is_valid():
			edit_object.User = request.user
			edit_object.Title = form.cleaned_data['Title']
			edit_object.Description = form.cleaned_data['Description']
			edit_object.Duedate = form.cleaned_data['Duedate']
			edit_object.Duetime = form.cleaned_data['Duetime']
			edit_object.save()
			return HttpResponseRedirect('/')
		else:
			form = EntryForm(initial={'Title': edit_object.Title, 'Description':edit_object.Description, 'Duedate':edit_object.Duedate, 'Duetime':edit_object.Duetime}) 
			return render_to_response("form.html",{"form": form, "object_id":object_id, "username":username}, context_instance=RequestContext(request))

	else:
		raise Http404
########################################################################################
def todolist_delete(request, object_id):
	if request.user.id is  None:
		#return HttpResponseNotFound('<h2>Please Login</h2>')
		return HttpResponseRedirect('/login/')

	try:
		del_object = TodoEntry.objects.get(id=object_id)
	except ObjectDoesNotExist, e:
		raise Http404

	if del_object.User.id == request.user.id:
		del_object.delete()

	return HttpResponseRedirect('/')

########################################################################################
def todolist_done(request, object_id):
	if request.user.id is  None:
		#return HttpResponseNotFound('<h2>Please Login</h2>')
		return HttpResponseRedirect('/login/')

	try:
		sw_object = TodoEntry.objects.get(id = object_id)
	except ObjectDoesNotExist, e:
		raise Http404

	if sw_object.User.id == request.user.id:
		if sw_object.Status == 'OPEN':
			sw_object.Status='DONE'
		else:
			sw_object.Status='OPEN'
		sw_object.save()

	return HttpResponseRedirect('/')

www/todolist/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <img src='/static/banner.gif' />
    <title>{% block sitetitle %}{% endblock sitetitle %}</title>
    <meta charset="UTF-8">
	<meta name="description" content="sinnloses zeugs">
	<meta name="keywords" content="FHStP, WEBTECH, ILV">
	<meta name="author" content="MG/TP">
	<link rel="stylesheet" href="/static/stylesheet/screen.css" />
</head>
<body>
<div class='wrapper'>
	<header>
		<nav id= 'user'>
		f&uuml;r Benutzer: {{username}}
		<ul>
			<li><a href="{% url 'todolist_add' %}" class="add icon-plus-circle"></a></li>
			<li><a href="{% url 'logout' %}" class="logout icon-logout"></a></li>
		</ul>
		</nav>
    	<br>
    	<h1><a href="{% url 'overview' %}">{% block title %}{% endblock title %}</a></h1>
		<br><br>
  	</header>
    {% block content %}{% endblock content %}
</div>
</body>
</html>

www/todolist/templates/form.html
{% extends "base.html" %}

{% block title %}&Uuml;bersicht{% endblock %}
{% block sitetitle %}TODOlist{% endblock %}

{% block content %}
<section>
<nav>
<ul>
{% if object_id %}

	<li><a href="{% url 'todolist_delete' object_id=object_id %}" class='icon-minus-circle'></a></li>

{% endif%}

	<!--<li><a href="{% url 'todolist_overview' %}">back</a></li> -->
</ul>
</nav>
<br>
<form method='POST' action='.'>{% csrf_token %}

<p class="help">(* = Pflichtfeld)</p><br>

	<div class="row {% if form.Title.errors %}error{% endif %} cell title">
		<label for="id_Title">Titel des Eintrages *</label><br>
		<p class="field">{{ form.Title }}</p>
		{% if form.Title.errors %}
			<ul>
				<li class='err'>Sie müssen einen Titel angeben!</li>
			</ul>
		{% endif %}
	</div>
	<div class="row {% if form.Description.errors %}error{% endif %}">
		<label for="id_Description">Beschreibung *</label><br>
		<p class="textarea">{{ form.Description }}</p>
		{% if form.Description.errors %}
			<ul>
				<li class="err">Sie müssen noch eine Beschreibung angeben!</li>
			</ul>
		{% endif %}
	</div>
	<div class="row">
		<div class="cell {% if form.Duetime.errors %}error{% endif %} time">
			<label for="id_title">Fälligkeitszeitpunkt</label><br>
			<p class="field">{{ form.Duetime }}</p>
			<p class="help">(Uhrzeit muss im Format HH:MM:SS eingegeben werden.)</p>
			{% if form.Duetime.errors %}{{ form.duetime.errors }}{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="cell {% if form.Duedate.errors %}error{% endif %} date">
			<label for="id_Duedate">Fälligkeitsdatum *</label><br>
			<p class="field">{{ form.Duedate }}</p>
			<p class="help">(Datum muss im Format MM/TT/JJJJ oder JJJJ-MM-TT eingegeben werden.)</p>
			{% if form.Duedate.errors %}
			<ul>
				<li class="err">Sie müssen auch ein Fälligkeitsdatum angeben!</li>
			</ul>
			{% endif %}
		</div>
	</div>

	<button type='submit' class='icon-ok'></button>

</form>
</section>
{% endblock content %}

www/todolist/templates/index.html
{% extends 'base.html' %}
{% block title %}Log in{% endblock %}
{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap/css/signin.css" />
{% endblock %}
{% block content %}
  <form action="" class="form-signin" method="post">{% csrf_token %}
      <h3 class="form-signin-heading text-center">Please log in</h3>
      {% if form.non_field_errors %}
          <div class="alert alert-danger">
            {{ form.non_field_errors|striptags }}
          </div>
      {% endif %}
      {% if not form.username.errors %}
        <input id="id_username" name="username" type="text" class="form-control" placeholder="Username (admin)" autofocus>
      {% else %}
        <div class="form-group has-error">
          {% for error in form.username.errors %}
            <label class="control-label" for="id_username">{{ error }}</label>
          {% endfor %}
          <input id="id_username" name="username" type="text" class="form-control" placeholder="Username (admin)" autofocus>
        </div>
      {% endif %}
      {% if not form.password.errors %}
        <input id="id_password" name="password" type="text" class="form-control" placeholder="Password (admin)" autofocus>
      {% else %}
        <div class="form-group has-error">
          {% for error in form.password.errors %}
            <label class="control-label" for="id_password">{{ error }}</label>
          {% endfor %}
          <input id="id_password" name="password" type="text" class="form-control" placeholder="Password (admin)">
        </div>
      {% endif %}
      
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    </form>
  </form>
{% endblock %}

www/todolist/templates/login.html
{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
       </table>

       <input type="submit" value="login" />
       <input type="hidden" name="next" value="{% url 'overview' %}" />
   </form>

{% endblock %}

www/todolist/templates/logout.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-success">You are successfully logged out</div>
<a href='/login'>Log in</a>
{% endblock %}